name: Build and Release APKs

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Log in to Expo
        run: cd Mobile-starter-Pack && expo login -u ${{ secrets.EXPO_CLI_USERNAME }} -p ${{ secrets.EXPO_CLI_PASSWORD }}
      
      - name: Build APK
        run: expo build:android
      
      - name: Release APK
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
          tag_name: ${{ github.ref }}
          repository: ${{ github.repository }}
